apiVersion: apps/v1
kind: Deployment
metadata:
  name: merwan
  annotations: submitted-by:merwan-juneydi-ugr0816
  labels:
    app: merwanweb
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merwanweb
      tier: frontend
  template:
    metadata:
      labels:
        app: merwanweb
        tier: frontend
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: devopsjourney1/merwanweb
          ports:
            - containerPort: 80
